05_SQS/tutorial_source/eb-django-express-signup/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('form.urls')),
]

05_SQS/tutorial_source/form/urls.py
from django.urls import path, re_path

from . import views

app_name = 'form'

urlpatterns = [
    # ex: /
    path('', views.home, name='home'),
    # ex: /signup
    path('signup', views.signup, name='signup'),
]

05_SQS/tutorial_source/form/models.py
from django.db import models
import boto3
import os
import logging


SQS_QUEUE_URL = os.environ['SQS_QUEUE_URL']

logger = logging.getLogger(__name__)


class Leads(models.Model):

    def insert_lead(self, email, latitude, longitude, infectedFlag):

        sqs = boto3.client('sqs')
                    
        try:
            response = sqs.send_message(
                QueueUrl=SQS_QUEUE_URL,
                DelaySeconds=10,
                MessageAttributes={
                    'email': {
                            'DataType': 'String',
                            'StringValue': email
                            },
                    'latitude': {
                            'DataType': 'String',
                            'StringValue': latitude
                            } ,
                    'longitude': {
                            'DataType': 'String',
                            'StringValue': longitude
                            } ,
                    'infectedFlag': {
                            'DataType': 'String',
                            'StringValue': infectedFlag
                            } 
                },
                MessageBody=(
                    'individuals database to warn possible infected people'
                )
            )
        except Exception as e:
            logger.error(
                'Error adding item to sqs: ' + (e.fmt if hasattr(e, 'fmt') else '') + ','.join(e.args))
            return 403
        status = response['ResponseMetadata']['HTTPStatusCode']
        if status == 200:
            if 'Attributes' in response:
                logger.error('Existing item updated to database.')
                return 409
            logger.error('New item added to database.')
        else:
            logger.error('Unknown error inserting item to database.')

        return status

05_SQS/tutorial_source/form/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import Leads


def home(request):
    return render(request, 'index.html')


def signup(request):
    leads = Leads()
    status = leads.insert_lead(request.POST['email'], request.POST['latitude'], request.POST['longitude'] , request.POST['infectedFlag'])
    return HttpResponse('', status=status)

05_SQS/tutorial_source/form/templates/generic.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon.ico' %}" />
    <title>Cloud Computing</title>
    <!-- https://www.bootstrapcdn.com/ -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Bootstrap Lumen theme -->
    <link href="https://maxcdn.bootstrapcdn.com/bootswatch/4.0.0-beta.3/lumen/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-lBO0+E/aIJhpRIYjP6dJ1mNYgo3hhUBPcF74XRfOM27g7WmDuitolvnUENdDG4QI" crossorigin="anonymous">
    <!-- Bootstrap fonts -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark bg-primary">
    <div class="container">
        <a href="../" class="navbar-brand">Cloud Computing</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav">
                <li class="nav-item active"><a class="nav-link active" href="{% url 'form:home' %}">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="#">About</a></li>
                <li class="nav-item"><a class="nav-link" href="#">Blog</a></li>
                <li class="nav-item"><a class="nav-link" href="#">Press</a></li>
            </ul>
        </div>
    </div>
</nav>
<main role="main">
    <div class="jumbotron" id="newstartup">
        <div class="container">
            <h1 class="display-3">Tutorial Group: Tuesday 9:00</h1>
        </div>
    </div>
    <div class="container">
        {% block contents %}<!-- /contents -->{% endblock %}
        <hr>
        <footer id="footer">
            <div class="row">
                <div class="col-lg-12">
                    <p>&copy; 2020_Project_Tue_9_00
                        <span class="pull-right">Made with
                            <a target="_blank" href="http://getbootstrap.com/">Bootstrap 4</a>
                        using <a target="_blank" href="https://bootswatch.com/lumen/">Lumen</a> theme.</span>
                    </p>
                </div>
            </div>
        </footer>
    </div>
</main>
<!-- Jquery Scripts -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Bootstrap core Scripts -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js"
        integrity="sha384-feJI7QwhOS+hwpX2zkaeJQjeiwlhOP+SdQDqhgvvo1DsjtiSQByFdThsxO669S2D"
        crossorigin="anonymous"></script>
{% block scripts %}<!-- /scripts -->{% endblock %}
</body>
</html>

05_SQS/tutorial_source/form/templates/index.html
{% extends "generic.html" %}
{% block contents %}
    <div class="row justify-content-md-center">
        <div class="col-sm-8">
            <div id="signupSuccess" class="alert alert-success" style="display:none">
                <p id="signupSuccessText">Thanks for helping!<br/>
                    The information will use to warn people you could have crossed.</p>
            </div>
            <div id="signupDuplicate" class="alert alert-success" style="display:none">
                <p id="signupDuplicateText">You already help others to be warned!<br/>
                    Stay at home until you feel better.</p>
            </div>
            <div id="signupError" class="alert alert-info" style="display:none">
                <p id="signupErrorText">Well this is embarrassing.<br/>
                    We couldn't process your request.</p>
            </div>
            <div class="jumbotron" id="jumbohome">
                <h1>Covid-19 Warning System</h1>
                <div class="row">
                    <div class="col-sm-9">
                        <p class="lead">The application is a database of individuals either infected or not.</p>
                        <p>Send us your mail, location and status to search for possible infections</p>
                        <p><a class="btn btn-lg btn-success" data-toggle="modal" href="#signupModal">INSERT DATA</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal" tabindex="-1" role="dialog" id="signupModal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Provide a few details and we'll be in touch...</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form id="signupForm" role="form">
                        <div class="form-group">
                            <label for="email">Email address</label>
                            <input type="email" class="form-control" id="email" name="email"
                                   placeholder="Your email address">
                        </div>
						<div class="form-group">
                            <label for="latitude">Latitude</label>
                            <input type="text" class="form-control" id="latitude" name="latitude" placeholder="Latitude">
                        </div>
						<div class="form-group">
                            <label for="longitude">Longitude</label>
                            <input type="text" class="form-control" id="longitude" name="longitude" placeholder="Longitude">
                        </div>
                        <div class="form-group">
                            <label for="infectedFlag">Did you test positive?</label>
                            <select class="form-control" name="infectedFlag" id="infectedFlag">
                                <option>Yes</option>
                                <option>No</option>
                            </select>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button id="signup" type="button" class="btn btn-primary">Confirm</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    {% csrf_token %}
    <script type="text/javascript">
        var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();

        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

        $(document).ready(function () {
            $.ajaxSetup({
                beforeSend: function (xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });
            $("#signup").click(function () {
                $.post("{% url 'form:signup' %}", $("#signupForm").serialize(),
                    function (data) {
                        $("#signupSuccess").show();
                    }
                )
                    .error(function (xhr) {
                        switch (xhr.status) {
                            case 409:
                                $("#signupDuplicate").show();
                                break;
                            default:
                                $("#signupError").show();
                        }
                    })
                    .always(function () {
                        $("#signupModal").modal('hide');
                    });
            })
        })
    </script>
{% endblock %}